name: test80
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ffc221'
    - '#d063a6'
    - '#8da3d5'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.101132330019027
purpose: []
